<footer class="footer">

    <p>
        <strong>Jira project link:</strong>
        <a target="_blank"
           href="https://cos10026assignmentpart1.atlassian.net/jira/software/projects/SCRUM/summary">
            <strong>https://cos10026assignmentpart1.atlassian.net</strong>
        </a>
    </p>

    <p>
        <strong>Github Repository link:</strong>
        <a target="_blank"
           href="https://github.com/Tuan-Dat-Quach/COS10026---Applied-Web-Project-Part-1">
            <strong>https://github.com/Tuan-Dat-Quach/COS10026---Applied-Web-Project-Part-1</strong>
        </a>
    </p>

    <p>
        <strong>Another way to Contact us?</strong>
        Please mail to:

        <a href="mailto:info@greenersociety.org">
            <strong>info@greenersociety.org</strong>
        </a>
    </p>

    <br>

    <p>
        &copy; 2026 Greener Society. All rights reserved.
    </p>

</footer>

</body>

</html>