<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="description"
        content="Recruitment Website for Greener Society! Here you can find out about the company's details, and of course, the opportunity to participate with us in conserving the environment!">

    <meta name="keywords"
        content="Environmental Conservation, GS, Greener Society, Protect Environment, Recruitment">

    <meta name="author"
        content="TideTech Group">

    <title>Greener Society - Recruitment Website</title>

    <link rel="stylesheet" href="styles/styles.css">

</head>

<body>

<header class="navigation">

    <figure>
        <img id="company_logo"
             src="Images/Official_Company_Logo.png"
             alt="Greener Society's Company Logo">
    </figure>

    <?php include 'nav.inc'; ?>

</header>