<nav aria-label="Main navigation">
    <ul id="menu">
        <li>
            <a href="index.php">
                <span aria-hidden="true">🪴</span> Home
            </a>
        </li>

        <li>
            <a href="jobs.php">
                <span aria-hidden="true">📝</span> Jobs
            </a>
        </li>

        <li>
            <a href="apply.php">
                <span aria-hidden="true">📄</span> Apply
            </a>
        </li>

        <li>
            <a href="about.php">
                <span aria-hidden="true">👥</span> About
            </a>
        </li>
    </ul>
</nav>